{{- define "common.istio_base" -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: product-composite-require-jwt
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  rules:
  - {}
  selector:
    matchLabels:
      app.kubernetes.io/name: product-composite
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Values.namespace }}
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: product-composite-request-authentication
  namespace: {{ .Values.namespace }}
spec:
  jwtRules:
  - forwardOriginalToken: true
    issuer: {{ .Values.jwtIssuerUri }}
    jwksUri: {{ .Values.jwtTokenEndpoint }}
  selector:
    matchLabels:
      app.kubernetes.io/name: product-composite
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.namespace }}-gw
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - minikube.me
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: hands-on-certificate
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.namespace }}-vs
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - {{ .Values.namespace }}-gw
  hosts:
  - minikube.me
  http:
  {{- range .Values.httpRoutes }}
  - match:
    {{- range .match }}
    - uri:
      {{- if .uri.prefix }}
        prefix: {{ .uri.prefix }}
      {{- else if .uri.regex }}
        regex: {{ .uri.regex }}
      {{- end }}
    {{- end }}
    {{- if .rewrite }}
    rewrite:
      uriRegexRewrite:
        match: {{ .rewrite.uriRegexRewrite.match }}
        rewrite: {{ .rewrite.uriRegexRewrite.rewrite }}
    {{- end }}
    route:
    {{- range .route }}
    - destination:
        host: {{ .destination.host }}
        {{- if .destination.port }}
        port:
          number: {{ .destination.port.number }}
        {{- end }}
    {{- end }}
  {{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: health-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "health.minikube.me"
    port:
      number: 443
      name: https-health
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.namespace }}-certificate
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: health-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "health.minikube.me"
  gateways:
  - health-gateway
  http:
  - route:
    - destination:
        host: product-composite
        port:
          number: 4004
{{- end -}}