secrets:
  rabbitmq-credentials:
    SPRING_RABBITMQ_USERNAME: rabbit-user-dev
    SPRING_RABBITMQ_PASSWORD: rabbit-pwd-dev

  mongodb-credentials:
    SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE: admin
    SPRING_DATA_MONGODB_USERNAME: mongodb-user-dev
    SPRING_DATA_MONGODB_PASSWORD: mongodb-pwd-dev

  mysql-credentials:
    SPRING_DATASOURCE_USERNAME: mysql-user-dev
    SPRING_DATASOURCE_PASSWORD: mysql-pwd-dev

  postgres-credentials:
    SPRING_DATASOURCE_USERNAME: postgres-user
    SPRING_DATASOURCE_PASSWORD: postgres-pwd

  redis-credentials:
    SPRING_DATA_REDIS_PASSWORD: redis-password

auth-server:
  envFromSecretRefs:
    - rabbitmq-credentials

product:
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials
    - redis-credentials

recommendation:
  envFromSecretRefs:
    - rabbitmq-credentials
    - mongodb-credentials
    - redis-credentials

review:
  envFromSecretRefs:
    - rabbitmq-credentials
    - postgres-credentials
    - redis-credentials

product-composite:
  envFromSecretRefs:
    - rabbitmq-credentials
  requests:
    memory: 600Mi
  limits:
    memory: 1200Mi

destinationRules:
  - name: product-composite
  - name: auth-server
  - name: product
  - name: recommendation
  - name: review

namespace: hands-on

httpRoutes:
  - match:
      - uri:
          prefix: /oauth2
    route:
      - destination:
          host: auth-server
  - match:
      - uri:
          prefix: /login
    route:
      - destination:
          host: auth-server
  - match:
      - uri:
          prefix: /error
    route:
      - destination:
          host: auth-server
  - match:
      - uri:
          prefix: /product-composite
    route:
      - destination:
          host: product-composite
          port:
            number: 80
  - match:
      - uri:
          prefix: /estate
    route:
      - destination:
          host: estate.hy-oltp.svc.cluster.local
          port:
            number: 80

jwtIssuerUri: http://auth-server # https://dev-a2z2mux06zphbdxf.us.auth0.com/
jwtTokenEndpoint: http://auth-server.hands-on.svc.cluster.local/oauth2/jwks # https://dev-a2z2mux06zphbdxf.us.auth0.com/.well-known/jwks.json