spring:
  application:
    name: product
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://config-server:8888
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 10000
        maxAttempts: 20
      username: ${CONFIG_SERVER_USR}
      password: ${CONFIG_SERVER_PWD}

---

spring:
  config:
    activate.on-profile: docker
  cloud:
    config:
      uri: http://config-server:8888