apiVersion: v2
appVersion: "1.0"
description: A Helm chart for added definitions in redis
name: redis-insight
version: 1.0.0

dependencies:
  - name: common
    version: 1.0.0
    repository: file://../../../common