spring.application.name:
  auth-server

server:
  port: 9999
  forward-headers-strategy: framework

app:
  eureka:
    username: u
    password: p
    server: localhost

eureka:
  client:
    service-url:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@${app.eureka.server}:8761/eureka/"
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: "ALWAYS"

logging:
  level:
    root: INFO

---

spring:
  config:
    activate.on-profile: docker

app:
  eureka:
    server: eureka
